### PR TITLE
Initial support for osl-netboot

### PR DESCRIPTION
**Pull request by ramereth**
This sets up a tftp server and razor on a machine for netbooting. It's intended to have host specific recipes for actual deploying which tie in osl-dhcp recipes as well. This is needed for the Facebook racks initially.

NOTE: The integration test is a little wonky due to the app. Not sure how to work around it but if you wait after converging for a bit and then run verify a few times it finally passes.

TODO:

- [x] tftpboot firewall rule osuosl-cookbooks/firewall#76
- [x] razor firewall rule osuosl-cookbooks/firewall#77

### CODE REVIEW

**Comment by ramereth** [comment]
[Milne: Facebook PXE environment](https://trello.com/c/LHKTh1Cu/189-milne-facebook-pxe-environment)

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs please review

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs should be ready for a final review

**Comment by ramereth** [comment]
@fahlmant please give it another try.

**Comment by ramereth** [comment]
!bump major

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v1.0.0.  Have a nice day!

**Pull request merged**
