### PR TITLE
Workstation preseed fixes

### PR DESCRIPTION
**Pull request by ramereth**

### CODE REVIEW

**Comment by fahlmant** [comment]
@ramereth what are these changes doing?

**Comment by ramereth** [comment]
@fahlmant please read the commit messages but basically I put the package installs in the wrong place in the preseed file. And then then boot script had some errors which these fix that I confirmed doing a local install on a VM.

**Comment by ramereth** [comment]
!bump patch *

**Comment by ramereth** [comment]
!bump patch *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.2.5.  Have a nice day!

**Pull request merged**
