### PR TITLE
OSL Workstation PXE setup for Razor

### PR DESCRIPTION
**Pull request by ramereth**

### CODE REVIEW

**Comment by ramereth** [comment]
[Milne: Workstation PXE environment](https://trello.com/c/R2QfMo5e/204-milne-workstation-pxe-environment)

**Comment by fahlmant** [comment]
@ramereth Can we get a bit of explination? I'm not really sure what this is doing, and the things added to the rakefile for example needs clarification.

**Comment by ramereth** [comment]
@fahlmant This is doing a few tihngs

1. Creates a workstation [Razor Task](https://github.com/puppetlabs/razor-server/wiki/Tasks) which includes the preseed we use in our current environment
2. Copies any files for brokers or hooks we may end up using eventually
3. Creates a chef-provisioning rake task which spins up a fully functioning Virtualbox VM to use with testing the platform. The VM has a second interface that's using the internal network feature of vbox.

I've been testing it by creating a PXE VM that is ONLY connected to the same internal network as the razor server. Your comment has made me realize I probably should make that vm with chef-provisioning as well.

Right now it takes a few manual steps on the razor server to actually setup and get all the bits working. My plan is to eventually make a custom resource to manage that so that it's more fully automated. In addition, it might be good to update the docs in the cookbook to reflect this.

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs ready for your review and testing. Please look at the README for instructions on how to test this.

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs any further commment?

**Comment by ramereth** [comment]
!bump minor *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.2.0.  Have a nice day!

**Pull request merged**
